### ISSUE TITLE
[Waterline] Can't create nested collection problems

### ISSUE THREAD

**Issue by malikid** [balderdashy/sails#2131]
Environment
===
sails: 0.10.4
sails-mysql: 0.10.5

Problem 1
===
Can't create nested collection while setting attribute 'autoPK' to false in nested Collection.

Source code
---
**TrackPixel.coffee**
```
module.exports =

  autoPK: false

  attributes:
    id:
      type: 'int'
      required: true
      primaryKey: true

    trackTargets:
      via: "trackPixel"
      collection: "TrackTarget"
```
**TrackTarget.coffee**
```
module.exports =

  autoPK: false

  attributes:
    id:
      type: 'int'
      required: true
      primaryKey: true

    trackPixel:
      model: 'TrackPixel'
```
**Test.spec.coffee**
```
describe "test track pixel model", ->
  it "test create with trackTarget", (done) ->
    trackPixelParam =
      trackTargets: [
        { 
          trackPixel: 3
          id: 4
          createdAt: '2014-08-18T11:40:20.000Z'
          updatedAt: '2014-08-18T11:40:20.000Z'
        }
        {
          trackPixel: 3
          id: 5
          createdAt: '2014-08-18T11:40:20.000Z'
          updatedAt: '2014-08-18T11:40:20.000Z'
        }
      ]
      id: 3
      createdAt: '2014-08-18T11:40:20.000Z'
      updatedAt: '2014-08-18T11:40:20.000Z'

    TrackPixel.create(trackPixelParam).exec (error, result) ->
      TrackPixel.findOne(result.id).populate("trackTargets").exec (error, trackPixel) ->
        trackPixel.trackTargets.length.should.be.equal 2
        done()
```
Test 
```mocha Test.spec.coffee```
will fail.

**Is this an expected result?**

Problem 2
===
Can't create nested collection while there is attribute 'id' in object expected to be created.

Source code
---
**TrackPixel.coffee**
```
module.exports =

  autoPK: false

  attributes:
    id:
      type: 'int'
      required: true
      primaryKey: true

    trackTargets:
      via: "trackPixel"
      collection: "TrackTarget"
```
**TrackTarget.coffee**
```
module.exports =

  attributes:
    trackPixel:
      model: 'TrackPixel'
```
**Test.spec.coffee**
```
describe "test track pixel model", ->
  it "test create with trackTarget", (done) ->
    trackPixelParam =
      trackTargets: [
        { 
          trackPixel: 3
          id: 4
          createdAt: '2014-08-18T11:40:20.000Z'
          updatedAt: '2014-08-18T11:40:20.000Z'
        }
      ]
      id: 3
      createdAt: '2014-08-18T11:40:20.000Z'
      updatedAt: '2014-08-18T11:40:20.000Z'

    TrackPixel.create(trackPixelParam).exec (error, result) ->
      TrackPixel.findOne(result.id).populate("trackTargets").exec (error, trackPixel) ->
        trackPixel.trackTargets.length.should.be.equal 1
        done()
```
Test
```mocha Test.spec.coffee```
will fail.

**Is this an expected result?**
