### ISSUE TITLE
css image not rendered

### ISSUE THREAD

**Issue by vanbungkring** [balderdashy/sails#342]
Hi All, i've create simple css like this

``` css
 .accepted{
      background: url('../images/accept.png') no-repeat;
      width: 20px;
      height: 20px;
    }
```

and guess what, image not showing, after inspect with Chrome

``` text
Resource interpreted as Image but transferred with MIME type text/html: "http://127.0.0.1:3000/assets/images/accept.png". 
```

i put image folder on /assets/image/
